### ISSUE TITLE
多个 API 的返回信息不明确

### ISSUE THREAD

**Issue by baitouwei** [cuter44/muuga#1]
虽然部分 API 的返回信息有链接到对应 JavaDoc，但是太『难看』了，而且 JavaDoc 页面也没对返回哪些字段进行描述。

**Comment by cuter44** [comment]
Codebase 经历几个版本无法避免格式不统一的问题, 将会陆续进行修正

**Comment by cuter44** [comment]
↑ 试图引入目前的最佳实践, 请参照 [改良的范例](http://120.24.234.213:8080/muuga/javadoc/com/github/cuter44/muuga/contract/servlet/TradeCreate.html) 提出建议, 如果认为可接受, 将会依照此方式修缮剩余的文档.  
@baitouwei

**Comment by cuter44** [comment]
超过响应时限, 认为已解决.
