### ISSUE TITLE
『意愿』相关接口改进

### ISSUE THREAD

**Issue by baitouwei** [cuter44/muuga#12]
可以将『意愿』的多个接口合并为一个以减少请求次数，具体就是弄一个字段来表明客户端要进行的操作。比如该字段为 deal，用4位二进制来表示所有的操作。

**Comment by cuter44** [comment]
驳回, 因为可能要支持更多的交易模式, 这样会产生过多的约定.  
还有就是, 要用这种模式也就必需要撰写位操作的SQL, 这会把代码弄得很脏.
