### ISSUE TITLE
/contract/search.api 接口的文档中 clazz 有什么值？

### ISSUE THREAD

**Issue by baitouwei** [cuter44/muuga#14]

**Comment by cuter44** [comment]
具体交易类型的非全限定类名, 目前有以下合法值:
"BorrowerInitedLoan" // 借入方发起的借阅
"BuyerInitedTrade"  // 买方发起的买卖
"LenderInitedLoan"  // 借出方发起的借阅
"SellerInitedTrade"  // 卖方发起的买卖
和以下非法值
"ContractBase"  // 交易类型的基类
"LoanContract"  // 借阅
"TradeContract"  // 买卖

通常都不会出现非法值, 可以无视之.

此 issue 揭示了一个文档缺漏, 将在稍后修补.
