### ISSUE TITLE
/user/search.api

### ISSUE THREAD

**Issue by baitouwei** [cuter44/muuga#3]
这个 API 的只是用来在登录的时候获取用户信息？这样一般只会返回一个用户，应该不存在需要进行分页和排序的情况，用户应该只可以通过邮件或用户名登录，按照这种设计的话，我需要判断用户输入的是邮箱还是用户名。

**Comment by cuter44** [comment]
Context http://120.24.234.213:8080/muuga/javadoc/com/github/cuter44/muuga/user/servlet/UserSearch.html

该 API 可以被用于任何需要找到一个用户的账户信息的时候, 包括但不仅限于登录.  
为了能统一地维护, 所有搜索接口都支持排序和分页, 即使结果唯一也是.  
因此, 所有的搜索接口的所有参数都是可选的. (之前不是这样, 但正在逐渐变得这样  
的确需要由客户端判断输入的是邮箱还是用户名, 但因为两者的schema是互斥的, 所以其实并不会太麻烦. (并且现在用户名还没做上去...
